default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: school-tracker_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: school-tracker_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: school-tracker_production
  username: school-tracker
  password: <%= ENV['SCHOOL-TRACKER_DATABASE_PASSWORD'] %>
